name: CI
on: [push, pull_request]

jobs:
  Hardhat:
    runs-on: ubuntu-latest
    env:
      # These are just dummy values to prevent hardhat complaining about config issues
      MAINNET_RPC: NA
      GOERLI_RPC: NA
      SEPOLIA_RPC: NA
      FANTOM_RPC: NA
      FANTOM_TESTNET_RPC: NA
      AVALANCHE_RPC: NA
      SONIC_TESTNET_RPC: NA
      CELO_RPC: NA
      HEDERA_RPC: NA
      KAVA_RPC: NA
      ARBITRUM_RPC: NA
      BASE_RPC: NA
      OPTIMISM_RPC: NA
      POLYGON_RPC: NA
      BSC_RPC: NA
      TRON_RPC: NA
      PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: yarn install
        shell: bash
      - name: Deploy
        run: yarn deploy
      - name: Tests
        run: yarn test
